// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQEJznD6r295tU6d1Vj0W0wA7c91ZMk4',
    appId: '1:1064574915790:web:ee1732dcc0b7e63333ec9f',
    messagingSenderId: '1064574915790',
    projectId: 'isms-pvp',
    authDomain: 'isms-pvp.firebaseapp.com',
    storageBucket: 'isms-pvp.appspot.com',
    measurementId: 'G-CRPZP17WBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8308B-hRkIOSeSxtrl9ye0jovrNLVOBE',
    appId: '1:1064574915790:android:3366a6ee6f4d509c33ec9f',
    messagingSenderId: '1064574915790',
    projectId: 'isms-pvp',
    storageBucket: 'isms-pvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6rZ7bGwBiMOpyuCF6SMTKAL99_V9JHg',
    appId: '1:1064574915790:ios:46a209e3f533c15633ec9f',
    messagingSenderId: '1064574915790',
    projectId: 'isms-pvp',
    storageBucket: 'isms-pvp.appspot.com',
    androidClientId: '1064574915790-bb51ulg7ps66gt7do66e16jjghsccfmm.apps.googleusercontent.com',
    iosClientId: '1064574915790-c1tuq7eu2bf2hv9dg1te1v4mocvjdrfl.apps.googleusercontent.com',
    iosBundleId: 'com.isms.prod',
  );
}
